# Generated by Django 5.1.3 on 2024-12-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_password_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
